//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toa
    {
        public int MaToa { get; set; }
        public int MaTau { get; set; }
        public int SoGhe { get; set; }
        public string LoaiGhe { get; set; }
    
        public virtual Tau Tau { get; set; }
    }
}
